### PR TITLE
* by Elcotek - Error protection and log for Item Proc's

### PR DESCRIPTION
**Pull request by elcotek**

### CODE REVIEW

**Comment by dol-leodagan** [comment]
Thanks !

Just 2 minor things for me to Merge this :

- Change log.Error() to log.ErrorFormat(), string concatenation use a lot of memory...
- Display weapon.Template.Id_nb in messages log to have the primary key reference of the weapon.

You can further commit your master branch with these fix, the Pull Request will reference them automatically.

**Comment by Graveen** [comment]
Thank you Elcotek to do the effort to match our new GH infra :)

**Comment by elcotek** [comment]
Am 26.03.2016 um 13:45 schrieb dol-leodagan:
>
>   * Change log.Error() to log.ErrorFormat(), string concatenation use
>     a lot of memory...
>   * Display weapon.Template.Id_nb in messages log to have the primary
>     key reference of the weapon.
>
Hello Leodagan,

The Memory issue was a good point.

I think this is now solved.

**Comment by dol-leodagan** [comment]
It's all ok.

I'm Merging the PR...

**Pull request merged**
