### PR TITLE
Fix guild commands not working

### LINKED ISSUE #248: guild invites can't be send by guild leader
i'm the founder and guild leader
but when i try to invite an alt to my guild it says not high enough (and i'm rank 0)

### PR DESCRIPTION
**Pull request by NetDwarf**
Fixes #248

### CODE REVIEW

**Comment by NetDwarf** [comment]
@JVirant Could you please clarify intent in RegionListRequestHandler. This is a bit much magic 😁️ I guess it is an indirect version check, but yeah I can only guess.

**Comment by Graveen** [comment]
Thank you ! What is doing your fix ? LoadPlayer() was overwriting default guild permissions ? :D

**Comment by NetDwarf** [comment]
`GameClient.LoadPlayer` calls `GameClient.set_Player` which (among other things) deletes GamePlayer in `Guild.m_onlineGuildPlayers` and never adds it back. The result is, that you are shown to be in the guild, but for the game you're actually not in any guild.

**Comment by PeterV1982** [comment]
tried, and still not able to invite.
if you want i'm ingame

**Comment by NetDwarf** [comment]
This is earliest on Storm after next restart.

**Comment by FlintTards** [comment]
Tested on Storm - at 06:09 17/09-2020 

= it’s working again. 👍💪👏

**Pull request merged**
