### PR TITLE
Replace Power cost by Health Cost for savage spells in Delves

### PR DESCRIPTION
**Pull request by Lord-Seithenin**
Savage Class use Health instead of power for its spells, as a result, it should be indicated in the Delves.

### CODE REVIEW

**Comment by Lotendan** [comment]
Hello, thanks for the PR. Is this possible that this is a duplicate of #317 ?

**Comment by DOL-Avalonia** [comment]
Seems there are similarities yes, but this commit has been developed in a different project without knowing #317 would be proposed. My focus was to fix the Delves infos of the savage only.

**Comment by Lord-Seithenin** [comment]
Seems there are similarities yes, but this commit has been developed in a different project without knowing #317  would be proposed. My focus was to fix the Delves infos of the savage only.

**Comment by Lord-Seithenin** [comment]
I will actually remove this PR, because the results are similar in PR #317

**Pull request closed without merging**
