### PR TITLE
Add sell command

### PR DESCRIPTION
**Pull request by tegstewart**
Added a command to sell items to merchants.  Useful for macros.

### CODE REVIEW

**Comment by OntheDOL** [comment]
nice ;)

**Comment by Graveen** [comment]
This is /msell renamed to /sell or a rewrite ? :)

**Comment by tegstewart** [comment]
I didn't know /msell was a thing, so I wrote this from the ground up.

**Comment by Graveen** [comment]
just went to check /msell did nothing more or less.

[msell.txt](https://github.com/Dawn-of-Light/DOLSharp/files/5187198/msell.txt)

**Pull request merged**
