### PR TITLE
Fix DataQuest with no Money/XP Reward

### PR DESCRIPTION
**Pull request by NetDwarf**

### CODE REVIEW

**Comment by NetDwarf** [comment]
(Characterization) Tests are a lot broader than necessary for the fix. They were created during refactoring, but will still be valuable regardless. The refactoring is not incorporated. It is more sensible to publish the fix first and then the refactoring later. It seems like a good candidate for a bigger overhaul.

**Comment by Graveen** [comment]
:)
Can you see why appveyor is not correct ?
TY !

**Comment by NetDwarf** [comment]
Looking into it for quite some time :D

**Comment by NetDwarf** [comment]
Forgot to notify. It should now work.

**Comment by Graveen** [comment]
;)

**Pull request merged**
