### PR TITLE
Added Eligible Races

### PR DESCRIPTION
**Pull request by tegstewart**
Added missing eligible races, according  to 1.127e

### CODE REVIEW

**Comment by NetDwarf** [comment]
Hm, I am not able to find patch notes regarding this. Could you give me a pointer? :sweat_smile:

**Comment by tegstewart** [comment]
No patch notes, I went through the client and entered the combinations the client allows that DOL doesn't.

**Comment by tegstewart** [comment]
1.125 added six combos based on forum polls, which is kinda neat:

Highlander Infiltrator, Saracen Heretic, Dwarf Shadowblade, Valkyn Valkyrie,
 Sylvan Ranger, Graoch Champion


I missed the last one, as the client isn't letting me select minotaurs at all, maybe an EC thing?


I wonder if it would be better to move eligible races .  Maybe a DB table, and add a player command to display and switch to available races to bypass client restrictions entirely.

**Comment by NetDwarf** [comment]
I'd be in favor of only adding the ones mentioned in 1.125 for now. Having that in DB (customizable) would be indeed sensible.

**Pull request closed without merging**
