### PR TITLE
Create OnlineStatusUpdate.cs

### PR DESCRIPTION
**Pull request by Shauzia**
This script is a modified serverlistupdate for website player count pinger. Simply edit user, pass and url then place 3 php files in your ftp directory.

### CODE REVIEW

**Comment by Graveen** [comment]
Thank you Shauzia

**Comment by hunabku94** [comment]
In my oppinion, the place of this file is in User Files.

**Comment by Graveen** [comment]
Or in GameServerScripts. I prefer it because user files are greats, but they finally end up in non-visible / non-maintained scripts.

**Comment by Graveen** [comment]
Ok this is suitable for GameServerScripts alongside with WebUIupdate.cs - and i like the WebClient example available.
Shauzie (or anyone) can somebody include a serverinfo.php example ? Thus, we have both client AND server side example.

**Comment by Shauzia** [comment]
Here's the php files - Made a little tutorial to go with it
[phpfiles.zip](https://github.com/Dawn-of-Light/DOLSharp/files/819458/phpfiles.zip)

**Comment by Graveen** [comment]
Ok merged. I'll upload the files in the next commit. Thank you

**Pull request merged**
