### PR TITLE
Player command translations / Ability translation

### PR DESCRIPTION
**Pull request by Mavcraft**
Added LanguageMgr to several player commands.
New entries in table "languagesystem" needed!

Hi!
I added a couple of translations to commands and have attached a sql insert file for the english strings.
Hopefully everything is fine, I am new to Git.

[Languagesystem_commands.zip](https://github.com/Dawn-of-Light/DOLSharp/files/10083126/Languagesystem_commands.zip)

I thought I would create a new pull request for translanting the abilities, sorry.
Here the new table:
[LanguageAbility.zip](https://github.com/Dawn-of-Light/DOLSharp/files/10085208/LanguageAbility.zip)

### CODE REVIEW

**Comment by NetDwarf** [comment]
First of: Thank you for your contribution! :+1: 

I think abilities are mostly translated in `GameServer/language` if I'm not mistaken and this seems also like a nice place for slash command (description) translations.

**Comment by Mavcraft** [comment]
If I just would understand what I am doing here with Git...

How do I sync my fork again with the original, so that my changes in the fork are deleted and I can start from scratch?
Then I would try to use the language files you mentioned.

**Comment by NetDwarf** [comment]
See `git remote -v` and look which remote-name points to Dawn-of-Light. In this case I use the name `upstream`, it might be for example named `origin` in your case. 
If you do not have any upstream remote set up, you can quickly do it by: 
`git remote add upstream https://github.com/Dawn-of-Light/DOLSharp`

`git fetch upstream`
`git reset upstream/master`
`git restore .`

For further reading/quick overview:
https://github.com/Dawn-of-Light/DOLSharp/wiki/GitBashIntro
https://dangitgit.com/en

**Comment by Mavcraft** [comment]
Thanks alot!
That way I have restored my local repository and google helped me to reset my forked repository on GitHub, too.
I have created a new pull request where I have moved a couple of hard coded sentences into the langauge file.

**Pull request closed without merging**
