### PR TITLE
Stop pets from getting aggro out of LOS

### PR DESCRIPTION
**Pull request by tegstewart**
I reported this a while back, but it doesn't look like it was remedied: http://www.dolserver.net/viewtopic.php?f=5&t=23087&p=158981&hilit=pet+aggro+through+wall

This is a quick fix rather than resolving the underlying problem.  There may be other issues stemming from the underlying race condition Leo mentions, but fixing that is beyond my capabilities.

### CODE REVIEW

**Comment by Graveen** [comment]
Can't agree more !

**Comment by OntheDOL** [comment]
Where does this leave charmed pets? Im not sure they fall under GamePet

**Comment by tegstewart** [comment]
They probably don't.  Might have to check for ControlledNPC as well.

**Comment by Graveen** [comment]
I also don't think they. But such a fix is simple and should prevent a lot of bad aggro.

**Comment by OntheDOL** [comment]
They both use icontrolledbrain I believe so one check for that should cover both

**Comment by tegstewart** [comment]
Did a little testing, and my mentalist can't charm humanoids or undead, so I can't test this.

Methinks this just became one of  my famous "I just wanted to fix this one thing" PRs.  :-p

**Pull request merged**
